"""
Generated UI forms from Qt Designer .ui files.

This package contains Python modules generated by pyside6-uic from .ui files.
Recompile after modifications: python scripts/generate_ui.py (or right-click → Compile Qt UI file)
"""
